services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
  navbar:
    build:
      context: packages/navbar
      dockerfile: Dockerfile
    ports:
    - "5173:5173"
